### ISSUE TITLE
Direct Credit Card transactions from Server without a web client

### ISSUE THREAD

**Issue by karthik30** [braintree/braintree_php#104]
Hi All,

Is it still possible to post transactions directly from the server using creditCard parameter ?
The documentation here (https://developers.braintreepayments.com/reference/request/transaction/sale/php#credit_card) states that this is deprecated. Does that mean that without a client side implementation credit card transactions cannot be processed from server side by sending across the CC information directly to the BT server?
Also if the parameter is deprecated, does that mean it will eventually be phased out and not be in use at all ?

-Karthik

**Comment by kexline4710** [comment]
@karthik We encourage users to leverage [`paymentMethodNonce`'s][pmn] to create and manage [`PaymentMethod`'s][pm] so they can be eligible for the easiest level of [PCI compliance][pci].

However, if your integration does not involve a client side implementation, then yes, you can still post transactions using raw credit card data. Be sure you research the PCI implications of doing so. We do not have a timeline for removing support for any pre-existing deprecated integration method.

I'm closing this issue because I believe this answers all of the questions you posed, but do not hesitate to reach out to [support][support] if you have any additional questions about your integration or Braintree in general.

[pmn]: https://developers.braintreepayments.com/start/overview#payment-method-nonce
[pm]: https://developers.braintreepayments.com/reference/response/payment-method/php
[pci]: https://articles.braintreepayments.com/reference/security/pci-compliance
[support]: https://support.braintreepayments.com/
