### ISSUE TITLE
Clarification on dynamic descriptor validation and associated docs.

### ISSUE THREAD

**Issue by RikdeBoer** [braintree/braintree_php#116]
Hello team,
I started experimenting with Dynamic Descriptors (in the sandbox). They API works well, but I am finding some inconsistencies between validation errors and documentation.

One error I get for the Dynamic Descriptor Name part is:
*"Descriptor name must be 22 characters or shorter and can only contain letters and numbers."*

However, it appears that an asterisk is also allowed, or is in fact mandatory for both credit card and PayPal.
"abc" produces the above error message (although it conforms to what the error message says)
"abc\*" passes validation (althought it does not conform)
"abc*myproduct" also passes

It appears that the rule really is this (taken from another validation error message): 
*"Company name/DBA section must be either 3, 7 or 12 characters and the product descriptor can be up to 18, 14, or 9 characters respectively (with an * in between for a total descriptor name of 22 characters)."*

It the latter correct? Is an asterisk indeed mandatory, for PayPal and credit card? The documentation pages are similarly unclear in places.

On https://developers.braintreepayments.com/reference/request/transaction/sale/php I read:
*"The payment information displayed to a customer in their PayPal account overview does not contain the dynamic descriptor. The information displayed there is data the merchant has configured with PayPal directly (e.g. business name, email address, business contact details)."*
Does that mean that there is no point in using dynamic descriptors for PayPal transactions?

**Comment by raymondberg** [comment]
Hi, @rikdeboer, we're reviewing this internally, but have not yet validated it. We'll return with a status update or questions as soon as possible. Thanks for giving us feedback!

**Comment by danielwu426** [comment]
Hi @RikdeBoer ,

So just to confirm, you're finding an asterisk is required for PayPal transactions? We use PayPal REST API and map PayPal descriptors to the `soft_descriptor` param that can be found in the [PayPal Reference documentation](https://developer.paypal.com/docs/api/) - note it doesn't say any requirement about asterisks. If this is the case, we can update our documentation accordingly.

Regarding your last question, the wording we have in that paragraph can be improved. It's meant to state that the descriptors and information displayed to a customer when they log into their PayPal account profile are *not* set by our PayPal descriptor parameter. Our PayPal descriptor parameter sets the descriptor customers see in their credit card / bank statements.

**Comment by crookedneighbor** [comment]
I'm going to close this since we haven't received a response in over a month. 

@RikdeBoer, if you're still having issues, please feel free to re-open the issue.

**Comment by jackfuchs** [comment]
Still the same Issue for me. Still the same misleading error message. Still the same wording in all of the documentation. Still no clue, how to overcome this.

Guys, can you please grab someone not involved into the development process, sit him next to you and let him understand this stuff. Optimize the wording and maybe the logic accordingly. In both, the documentation and the validation error messages.

**Comment by JoshuaFlood** [comment]
@raymondberg @danielwu426 @crookedneighbor 

What @jackfuchs says is entirely the correct process for this. Documentation is rarely user-friendly and assumes that the user shares as much knowledge about the software/service as the person who wrote it. If this were the case, then there would be no need for documentation. I spend hours and sometimes days searching for solutions to easily-solved problems, simply because the person writing documentation assumes a level of comprehension that the user almost never has.

I haven't encountered the problem myself, because I haven't tested my configuration yet. I found this thread whilst attempting to find general information about formatting URL descriptors (because the URL of the site I'm designing is more than 13 characters) and it is quite concerning.

There is no particular point to my comment, I'm just bumping jackfuchs 🤓

**Comment by robkerr1992** [comment]
We ran into this same issue at my job. We were sending the same dynamic descriptor to braintree for our CAD and USD accounts which use different banks to process the payments. Turns out that each bank has different requirements for the descriptor. We ended up creating unique descriptors to send to the payment processor depending on which account we were using. If you run into this issue, make different descriptors. You can also call braintree support for help with the requirements.

**Comment by mikemcelligott** [comment]
Alright, well, based on some of this I did find a set of values that finally worked.  The documentation is close enough to cause you to waste hours thinking you're doing something unrelated wrong, super frustrating.   Just so you all can get on with your implementation testing, this worked for me on a mock visa transaction in the sandbox.  Obviously this input variable is stringified into: **variables {input: input}**.  The change was just to manually add the asterisk to the name, and I suspect have the total be less than 22 characters.

 ```
   let input = {
      paymentMethodId: paymentMethod.id,
      transaction: {
        amount: amount,
        descriptor: {
          name: "SaddlUp*",
          phone: "8005555555"
        }
      }
    };
```
