### ISSUE TITLE
Braintree_Exception_SSLCertificate

### ISSUE THREAD

**Issue by kbdavis07** [braintree/braintree_php#128]
Hi,

I am using the WHMCS module and getting the following error on live production website:

exception 'Braintree_Exception_SSLCertificate'

wwwroot\Order\modules\gateways\braintree\lib\Braintree\Http.php:94

wwwroot\Order\modules\gateways\braintree\lib\Braintree\Http.php(59)

The SSL cert is valid.

Expires on Friday, September 23, 2016.

**Comment by kexline4710** [comment]
@kbdavis07 Due to the way our library is structured, it is possible to receive this error when there are network issues or timeouts; however, if you are consistently receiving this error I recommend that you reach out to the [Braintree support][support] team to take a look at your integration, especially since this is in production.

[support]: https://support.braintreepayments.com

**Comment by kbdavis07** [comment]
I notice this happens more often when it is a cron run if that helps out any.

**Comment by kexline4710** [comment]
Hmm, I’m still not sure how that would affect things. I would reach out to [support][support] so that the team can talk through the specifics of your integration.

[support]: https://support.braintreepayments.com/
