### ISSUE TITLE
README uses PHP4 style class naming

### ISSUE THREAD

**Issue by rquadling** [braintree/braintree_php#129]
The README.md shows old-style PHP4 Capital_Snake_Case class names rather than PS4 style namespaces.

```
Braintree_Configuration::environment('sandbox');
Braintree_Configuration::merchantId('your_merchant_id');
Braintree_Configuration::publicKey('your_public_key');
Braintree_Configuration::privateKey('your_private_key');
```

used to be the perfectly good ...

```
Braintree\Configuration::environment('sandbox');
Braintree\Configuration::merchantId('your_merchant_id');
Braintree\Configuration::publicKey('your_public_key');
Braintree\Configuration::privateKey('your_private_key');
```

**Comment by jdlc** [comment]
Both PSR-0 and PSR-4 namespacing are supported in the client library, and we are displaying the older version to show it is still supported. Feel free to use PSR-4 namespacing when integrating with Braintree if that is your preference!

**Comment by rquadling** [comment]
Aha! Thank you.

**Comment by Taluu** [comment]
Hi there,

I'm sorry to reanimate a dead subject, but what you're saying here is that you would prefer having the devs use the old fashion way (psr-0 pear style classes) rather than encourage them to use psr-4...

If you really want to say "oh we support psr-0 too", you should put that kind of sentence below the example, instead of using deprecated example...

My 2 cents.

**Comment by michaelchiche** [comment]
@Taluu is right! We should look forward! not the past!
