### ISSUE TITLE
API modify date parameters on Transaction::search

### ISSUE THREAD

**Issue by jodarove** [braintree/braintree_php#135]
Im running this:
```php
// $startDate, $endDate have some value XX, YY
Braintree\Transaction::search(
    [Braintree\TransactionSearch::settledAt()->between($startDate, $endDate)]
);
// different than the call XX + 5h,  YY + 5h (in my case)
```
The function searches for transactions, everything as it should be, but... it modifies $startDate and $endDate.

This is the expected behavior?  

Library version: 3.9.0

**Comment by matthewpatterson** [comment]
Hey @jodarove,

It looks like the library is modifying the timezone of `$startDate` and `$endDate` by [setting it to UTC](https://github.braintreeps.com/braintree/braintree-php/blob/3.9.0/lib/Braintree/Xml/Generator.php#L133-L134). I can't really say if this is the expected behavior or not.

You can work around it by cloning the objects that you pass in:

```php
Braintree\Transaction::search(
    [Braintree\TransactionSearch::settledAt()->between(clone $startDate, clone $endDate)]
);
```

**Comment by jodarove** [comment]
Sure thing, that what i did, but i though to report it in case it was not expected to happen.
Thanks for your quick reply and keep the good work!

**Comment by matthewarkin** [comment]
I would argue that it is a bug / at least unexpected behavior, the change to startDate and endDate are just for internal Braintree use, and as a developer seeing side effects to those objects on that call would definitely unexpected.

**Comment by raymondberg** [comment]
This went out with 3.14.0. 

0c13b62
