### ISSUE TITLE
payment_method_nonce does not contain a valid payment instrument type

### ISSUE THREAD

**Issue by githoober** [braintree/braintree_php#137]
One of our customers tried to place an order with us, but calling Transaction::sale failed with a message:
"payment_method_nonce does not contain a valid payment instrument type.". Could someone elaborate on what exactly this message means because right now we have no way to determine what went wrong, how to reproduce it,  and more importantly how to prevent this from happening in future?

I tried to place an order with a fake nonce value of fake-android-pay-nonce, and got a different error message (Merchant account does not support payment instrument.). I think this means that a nonce contains a valid but unsupported instrument type wheres in our initial case the value of it was invalid, not one of those defined in \Braintree\PaymentInstrumentType

**Comment by pblesi** [comment]
Hi @githoober!

There are two causes for this error. One is that it could indicate a misconfiguration that is generating the error because we did not receive the appropriate parameters to indicate a valid payment instrument type such as CreditCard, PayPalAccount, AndroidPayCard, etc. 

The second cause of this, and probably the most likely in your case, is if we cannot determine which type of credit card was specified such as Amex, Visa, Discover, MasterCard. If we do not recognize the specified card number, then this error can be generated, and I think this was the issue in your case.

If you run into further issues, you should reach out to our [support team](https://support.braintreepayments.com/) for further help in getting things resolved.

**Comment by AlbertGhazaryan** [comment]
Hi there , I am using PayPal Powered by Braintree Version 2.0.1 (works in test mode), and WooCommerce Version 2.6.14 for some reason.
When user is guest he/she can submit order without any problem , yet when user is logged in he/she get the error bellow.
<<<<
Braintree (Credit Card) Payment Failed (Status code 91577, 81703, 81709, 81714, 81725: Merchant account does not support payment instrument., Credit card type is not accepted by this merchant account., Expiration date is required., Credit card number is required., Credit card must include number, paymentMethodNonce, or venmoSdkPaymentMethodCode.) Order status changed from Pending Payment to Failed.
>>>>
The most interesting thing is this while I was testing with different browsers payment getway behaviour is different. Opera can submit order , yet Firefox no being logged in with the same account.
Do you have any idea why it is happening so ?

**Comment by crookedneighbor** [comment]
@AlbertGhazaryan This sounds like an issue with your particular integration, not a problem with the SDK itself. You should [contact our support team](https://developers.braintreepayments.com/forms/contact) with the details of your integration. They are the most equipped to help you out.

**Comment by simeyla** [comment]
I've seen this error (just now) with a vaulted Apple Pay payment (was vaulted by mistake).

If you vault Apple Pay cards they can fail but a nicer error would be good :-)
I'm just going to delete it to solve the problem.

(Sandbox token: cxtnn3)
