### ISSUE TITLE
Page size when searching transactions

### ISSUE THREAD

**Issue by bensebborn** [braintree/braintree_php#153]
Hi

With reference to #150 

The default page size seems to be set to 50 records. We're reconciling a day's worth of transactions, and it can take 10-15 minutes to return all transactions

Based on 2000 transactions being returned, this is leading to 2000/50 = 40 roundtrips to the API, over SSL which is very slow.

We would appreciate a way of manually increasing the pagesize so we can more effectively query the API.

**Comment by jackellenberger** [comment]
Hi @bensebborn,

This is unfortunately a known issue that is not specific to the PHP client library. We are working on the gateway side to improve  search speed, but don't have an ETA at this time. 

We have the page size set at 50 to prevent what @bensebborn may have experienced [here](https://github.com/braintree/braintree_php/issues/150#issuecomment-256641012), where the search request times out at the database and causes the returned set to be incomplete. By splitting queries into chunks we can mitigate the chances of failing to collect a full page. We will discuss adding a parameter to more easily increase the page size, but you will need to check the length of the [ids array](https://github.com/braintree/braintree_php/blob/d6ce80f7f54abe9972d577173343d1975bc49e77/lib/Braintree/ResourceCollection.php#L152) you receive to verify that a full page was returned.

**Comment by bensebborn** [comment]
Thanks @jackellenberger .

I would say that currently, the page size is a big issue for us. We've had to move a lot of reconciliation jobs to be overnight, and if there's an issue and they need to be re-run, we're tying up the user for 10-15 mins waiting for it to run, then we fix the issue and have to run again.

This week I've tried to reconcile 5 days transactions and its taken best part of 3 days :o

Lets just say 'Bloody braintree is SO slow' is quite a common phrase when this happens!

Is there a hack we can use to manually increase this, bearing in mind the caveats you discussed?

**Comment by jobbrown** [comment]
+1 - Would love this.

**Comment by danakatz** [comment]
Thanks for the follow-up! There is no way to increase the page size from the client library — even if you manually changed it, the server would still only return 50 results, which could cause missing data and other unexpected behavior. 

We currently have no plans to make page size configurable. It would have performance consequences in addition to those already outlined here, including slower requests caused by increased serialization time on the server side.

All that said, we definitely understand that this is a problem, and I can assure you that we are actively working on internal improvements to alleviate the search issues.

**Comment by jobbrown** [comment]
I just want to bump this issue to ensure its still at the forefront of people's minds. 

Our reports are taking 15-20 minutes to run now over the Black Friday period due to increases in sales. 

It'd be nice if pulling out the data didn't take so long, especially when the amount of data is so little.

**Comment by danakatz** [comment]
Hey @jobbrown ! If you're not in touch already, I'd encourage you to reach out to [Braintree support](mailto:support@braintreepayments.com) — we might be able to offer some suggestions based on your specific use case.

**Comment by bensebborn** [comment]
Bumping this again, still causing us lots of issues when a report takes 20-30 minutes to run. When we're reconciling a month, that's 15 hours!

**Comment by jobbrown** [comment]
+1

**Comment by bensebborn** [comment]
Any movement on this 3 years later?

**Comment by jobbrown** [comment]
+1

**Comment by crookedneighbor** [comment]
Please reach out to our Support team, who can assist you directly in coming up with a custom reporting solution to better meet your needs.

https://help.braintreepayments.com/
