### ISSUE TITLE
Undefined property

### ISSUE THREAD

**Issue by jamesallsup** [braintree/braintree_php#171]
`Undefined property on Braintree\Transaction: riskData in /*******/*******/vendor/braintree/braintree_php/lib/Braintree/Base.php on line 49`

Seeing this in our log files several times, using 3.17.0 but checked over the newer releases and couldn't see anything related to this. I will try the update later this week but please advise if it is repeatable or has been fixed.

**Comment by bluk** [comment]
@jamesallsup Hi, it seems like you are trying to read the `riskData` from the `Transaction` in your code, but the data is not present in the response. This may be because the `Credit Card Fraud Tools` in the `Settings > Processing Options` in the Braintree Control Panel are not setup correctly.

Please contact [Braintree Support](https://articles.braintreepayments.com) at the bottom of that page to help configure the fraud tools.
