### ISSUE TITLE
Braintree_PaymentMethod::find() does not return a Result\Successful

### ISSUE THREAD

**Issue by theprivileges** [braintree/braintree_php#209]
### General information

* SDK/Library version: 3.25.0
* Environment: sandbox
* Language, language version, and OS: PHP 7.1 Ubuntu 16.04.3

### Issue description

On the [documentation](https://developers.braintreepayments.com/reference/response/payment-method/php) for `Braintree_PaymentMethod::find()` it is noted:
> Returned directly or within a successful [result object](https://developers.braintreepayments.com/reference/general/result-objects/php) from the following requests:

However, when calling `Braintree_PaymentMethod::find()` with a valid vaulted `token`, we are getting back the direct payment method object. 

Should not the API response from `Braintree_PaymentMethod::find()` be wrapped in `Result\Successful`? 

Our wrapper is checking to make sure we received a successful response from calling Braintree's API, but we noticed an error when calling `find()`.

Thank you.

**Comment by crookedneighbor** [comment]
This is expected behavior. The `find` methods return the object directly, rather than being wrapped in a result object. They raise a `Braintree_Exception_NotFound` exception when the object does not exist. That they return an object directly is shown in the example for the docs: https://developers.braintreepayments.com/reference/request/payment-method/find/php

The wording could be clearer though, so we'll make a change to the docs to clarify it.

**Comment by jaypatel512** [comment]
According to the documentation, we return Braintree_PaymentMethod either directly, or wrapped as a successful response object. The list of methods below includes both. 

In case of [Payment_Method:find()](https://developers.braintreepayments.com/reference/request/payment-method/find/php), we return the object directly.

**Comment by theprivileges** [comment]
@crookedneighbor Thank you for clarifying it.
