### ISSUE TITLE
How can I get an existing payment method from a payment method nonce?

### ISSUE THREAD

**Issue by carterbryden** [braintree/braintree_php#224]
### General information

* SDK/Library version: 3.28.0
* Environment: Sandbox
* Language, language version, and OS: PHP 7 on Ubuntu 14.04

### Issue description

I'm using the drop-in UI, which has no features for removing an existing payment method ( 👎 ) so I need to be able to find a payment method by the payment method nonce, which is all that the drop-in UI will give me.  

When I use Braintree_PaymentMethod::find(payment_method_nonce) it can't find the payment method. How can I get that existing payment method so that I can run Braintree_PaymentMethod::delete(payment_method_token)?

**Comment by crookedneighbor** [comment]
We're aware of the difficulty of managing payment methods on the client and are working on a solution.

In the mean time, there's a workaround you can use where you call [`paymentMethod()->create`](https://developers.braintreepayments.com/reference/request/payment-method/create/php) with a nonce that refers to a vaulted payment method and it will return the existing payment method rather than create a new one.

Stay tuned on https://github.com/braintree/braintree-web-drop-in/issues/391 for updates on deleting payment methods using Drop-in UI.
