### ISSUE TITLE
Use PSR-0 autoloader instead of loading classes manually

### ISSUE THREAD

**Issue by Etenil** [braintree/braintree_php#38]
Whenever a call is made that requires the class `Braintree`, then the dependencies are forcibly loaded.

This is pretty ugly. It would be much more elegant to provide an include file for people who do not use composer. This file can contain the [reference implementation](http://www.php-fig.org/psr/psr-0/) of the PSR-0 autoloader.

**Comment by jdahern** [comment]
Im all for this, however, I have two reserves about the change.

1) BrainTree is PHP 5.2 compatible, and Name space is not. (does not impact me)
2) PSR-0 is deprecated (not at the time of filling the bug) 

Having a branch that is still PHP 5.2 compatible, or changing the version to 3.0 for the PSR-4 method would be a better idea.
Jeff

**Comment by maxrice** [comment]
We use the Braintree SDK with WordPress which requires it to be PHP 5.2 compatible -- if there was a branch that is 5.2 compat and maintained the same as the master branch, that'd be fine :smile_cat:

**Comment by jdahern** [comment]
wow, dead issue for six months, and two comments back to back saying the same thing.

**Comment by ryanjpodonnell** [comment]
@jdahern,

We understand that dependency management is PHP 5.2 has lead to an inelegant way to load source files, but unfortunately due to legacy support we do not plan to upgrade our PHP Library to be compatible with PSR-4. We apologize for any inconveniences this may be causing you.

Best,
Ryan O'Donnell
Braintree Developer

**Comment by borfast** [comment]
Wait, @ryanjpodonnell, you «do not plan to upgrade our PHP Library to be compatible with PSR-4»? As in, at all, ever?

**Comment by ryanjpodonnell** [comment]
@borfast,

For now, we plan to stick with PHP 5.2 seeing that about one-fifth of all websites using PHP are still using this version. As the ecosystem progresses, we will reevaluate our decision.
When we do deprecate the use of PHP 5.2, we will definitely revisit this as a feature enhancement.

Ryan

**Comment by borfast** [comment]
@ryanjpodonnell, I respect your liberty to make that decision but I think it's the wrong one. It harms the ecosystem more than if you push people to upgrade, because if you don't, you're basically saying that it's OK to use a completely outdated language version, one that has been unsupported and thus unpatched for *four years*. What's the point? People in the PHP world are finally moving forward and becoming a bit brighter. Please help them, don't hold them back.

Anyway, what about the suggestion to create a separate branch to maintain 5.2 compatibility?

**Comment by jdahern** [comment]
I understand the need to keep a backwards compatible as far back as you can, but at the same time, any website that is  improving it's relationship with braintree is most not going to stay on 5.2, or 5.3 as 5.3 is EOL as well. One of the advantages of packet management (like composer) is that you can branch a 3.0 that is php 5.4 (maybe even 5.5 ) or greater, and security updates for 5.2 can still be pushed.

If a user wants a "new" feature of the API, then most likely, there not running a version of PHP that has not been touched in 4 year. 

also, new programs are starting with 5.4+

Im actually more surprised that braintree allows 5.2 considering the last update was 06 January 2011.

I would agree with @borfast, this holds back 3/4 of your user base and IMHO opens braintree to unnecessary security vulnerabilities

**Comment by mattjanssen** [comment]
I agree with @jdahern on these two points:

1) Allowing sites running PHP 5.2 to use Braintree is a security risk to users entering their sensitive data. This may even lead to liability issues for companies that continue to support software for these unpatched versions.

2) Not following a PHP standard that has been followed since 2010, and continues to gain adoption, will only aggravate future implementers of Braintree. Braintree's key selling point was to avoid developer aggravation.

**Comment by openbl** [comment]
You have a fair point that merchants who are upgrading their Braintree PHP library are likely to also be installing a modern version of PHP. However, we unfortunately don't currently track the language version that our libraries are being installed on to authoritatively know what the breakdown is. Some sources put the active installation base of PHP 5.2 around 19%[1], which is relatively substantial.

As a guiding principle, we try to EOL support for versions of a language that are no longer receiving security patches; PHP 5.2 and 5.3 fall into that category. PHP 5.4 is the latest supported version of PHP, which itself is going to be EOL'ed this year. Before deprecating support for 5.2 (and likely 5.3) and make autoloading a first-class feature of our library, we don't like the idea of maintaining separate branches, 5.2 compatible and 5.3+ compatible, since it adds to a maintenance burden that is greater than its benefit.

I realize this might be unsatisfactory response. We do hope to address these issues in a future release but need to be respectful to the merchants who are expecting our library to support PHP 5.2.

[1]: http://w3techs.com/technologies/details/pl-php/5/all

**Comment by borfast** [comment]
@openbl, but that's exactly the point: PHP 5.2 has almost 20% of installations precisely because we, as a community, don't push things forward. Remember the GoPHP5 "movement"? That made a huge difference and should have served as a lesson. Unfortunately we're too quick to forget.

In the end it boils down to this: not matter how many excuses we come up with to make it look politically and socially correct, it's *not* OK to run an outdated, unsupported and unpatched, 4+ years old version of a crucial piece of software in your we stack. It just doesn't make sense and those who do it deserve all the pain they will get from it.

The correct course of action, in my opinion, would be to create a 5.2 branch that will only get security updates, no new features, and support PHP 5.5 (or at most 5.4) in the master branch. If security issues crop up in the 5.2 line, they can be fixed there while a modern version of the library (hint: get rid of the static methods) can grow without being hindered by the "we-need-to-support-everyone" handicap.

I completely agree that maintaining two separate branches is not ideal but how is it any worse than effectively telling people that it is OK to run insecure software. This coming from a company that handles people's money. What does that tell you about Braintree's concerns for security?

I think this is what bothers me the most: some big players like Braintree, people/companies that have a considerable reach and visibility, are setting bad examples for the rest to follow. PHP has had enough of a bad reputation in the past and it still deserves a lot of it, some because the language itself is simply a mess, and most of it because some PHP users insist on perpetuating bad habits and setting bad examples.

This is one of them. Please don't do it.

**Comment by jdahern** [comment]
I don't mean to sound condescending when I say this, 

I now understand why we have had a recent rash of hackers able to break into site and steal sensitive credit card information. The processors are not requiring that the vendors stay some what up-to date with there security software.

Also remember that bumping major version is not a bad thing to drop outdated / unsecured dependancies, this is not 1990 where you only have one version of your code out, or CVS where going to an older version of the code base requires an act of god. This is 2015, where a programer can pick which version of the software they want, and going to an outdated branch is not that hard.

**Comment by eusonlito** [comment]
I have created a PSR-4 fork and I have the fork working in a project, but I need to update unitests.

If you want to test it, you are welcome. I can fix bugs and problems ASAP.

https://github.com/eusonlito/braintree_php

Regards.

**Comment by bryanagee** [comment]
@openbl, @ryanjpodonnell  - I realize this is closed, but wanted to ask if you've considered offering a legacy version that is 5.2+, and then launching an updated, PSR-4 version (possibly as 3.0)? 

I just cloned to take a look at the code, and being autoloaded has caused several headaches already--the unit tests don't run in a clean vagrant box because of a class re-declaration. As a developer evaluating client libraries, that is an immediate red flag. You may be serving that 19%, possibly at the cost of prospective clients who adhere to standards in their code bases.

**Comment by bryanagee** [comment]
Short of adopting PSR-4, you could ditch the include script and use composer's classmap autoloader.

**Comment by borfast** [comment]
@bryanagee, I wouldn't count on a reply. I think it is quite clear that unfortunately Braintree isn't interested in supporting a less outdated version of PHP and its good practices. :\

**Comment by bryanagee** [comment]
vim te

**Comment by bryanagee** [comment]
@borfast I completely understand your being discouraged--but you never know; it can't hurt to try, and every once in a while the old guard can make positive changes =).

**Comment by bryanagee** [comment]
On the upside, I did manage to get the tests somewhat running:

    tests/unit            : OK (188 tests, 443 assertions)
    tests/integration : FAILURES!
        Tests: 523, Assertions: 93, Failures: 19, Errors: 484.

**Comment by matthewpatterson** [comment]
Hey @bryanagee, supporting legacy PHP versions has actually been the subject of some recent conversations here at Braintree. We're in the process of deprecating support for PHP 5.2 and 5.3. This does involve some coordination on our end--for example, we need to ensure all of our documentation reflects the new version requirement--so it's not something that can happen overnight. We're pretty close, though.

With regard to the tests, our integration test suite can only be run by us, unfortunately, as it requires our internal services to be running locally.

**Comment by bryanagee** [comment]
@matthewpatterson -Thanks for the quick reply; sounds like there is indeed some positive change.

As far as the tests go, it may be helpful to note the unavailable dependencies somewhere... I will take a look and maybe shoot you a pull request on that.
