### ISSUE TITLE
Create Plans with API call

### ISSUE THREAD

**Issue by tarex** [braintree/braintree_php#59]
Hi ,
I'm creating a WordPress plugin where user can make subscription plan and they can add recurring billing system . Is there any way to create the plans dynamically into Braintree ?  i saw in the documentation that we can not create plans through the API .
I found other payment gateway has this option  . Is there any possibility to add this feature in future ? Thanks

**Comment by jdahern** [comment]
+1

**Comment by ryanjpodonnell** [comment]
Hello @tarex,

We have explored this option, however, due to how our recurring billing system is set up, it is a more efficient workflow to change a subscription at the time of creation. Almost every field for a subscription is over-writable so it is ideal to have fewer plans and more subscriptions (which can be created via the API).

Ryan O'Donnell
Braintree Developer

**Comment by jdahern** [comment]
Hi @ryanjpodonnell ,

I can see the reason why having few plans is a good thing, and in fact, when we can, we remove plans that are outdated / dont have any more users on them. My use case is more to the point of being able to sync production and sandbox plans automatically. We have less than 40 plans, so we can do it by hand, but its kinda weird when we could do it in a script. I would be happy with a copy plans from prod option, but that may not be realistic.
