### ISSUE TITLE
Setting currency when running Braintree_Transaction::sale()

### ISSUE THREAD

**Issue by rained23** [braintree/braintree_php#93]
Hi,

I am looking into Braintree documentations and cannot find anything that show
how to set the currency.

I am making module for Braintree so our users can use Braintree to accept payment.

What I get when checking around Braintree Sandbox, I just see the currency is set on top of Merchant account, as example currently its USD.

Let say if my user have Braintree merchant account with currency USD, while my platform is using different currency as example MYR.

If I set the amount in MYR value my user customers will be charged at USD right ? 

How to handle this use case if I cannot set any conversion or currency ?

**Comment by matthewpatterson** [comment]
Hey @rained23,

Transaction currencies are set at the merchant account level and can't be changed on a per-transaction basis, so if you want to run a transaction in MYR, you will need a separate merchant account in MYR.

For the Braintree Sandbox, this can be done pretty easily by following these instructions: https://articles.braintreepayments.com/get-started/currencies#testing-in-multiple-currencies

When you run a transaction, you'll need to [specify the merchant account](https://developers.braintreepayments.com/ios+php/guides/transactions#specify-merchant-account) you want to use for the transaction.

If you have any questions or need some extra help, feel free to reach out to our support team at support@braintreepayments.com.

-Matt

**Comment by rained23** [comment]
Hi @matthewpatterson ,

Thanks for the response, I just found out that link after posting this, 
first I thought there was missing documentation on that. 

I think this should go to your support team. Thanks.

**Comment by raymondberg** [comment]
Hi @rained23. We don't currently support that, and the value proposition seems low since changing a merchant account currency after the fact is not possible programmatically. Braintree support has to do that as part of a support request and this has effects on account functionality. As such, it will almost never change from initial configuration.

I would recommend you ask the person who manages your merchant account to provide the list of Merchant accounts with their currency settings. We will definitely consider it if we start exposing other parts of the merchant account management through the API.

**Comment by agfor** [comment]
I don't think this needed a response, it was just accidentally reopened.
