### ISSUE TITLE
Warnings when Customer is deleted

### ISSUE THREAD

**Issue by marcguyer** [braintree/braintree_php#95]
Here's a basic example that illustrates replicating this:

```php
Braintree_Configuration::environment('sandbox');
Braintree_Configuration::merchantId('[id]');
Braintree_Configuration::publicKey('[key]');
Braintree_Configuration::privateKey('[key]');
$result = Braintree_Customer::create(array(
  'firstName' =>'Test', 
  'lastName'  =>'Customer', 
  'email'     =>'test@example.com'
));
Braintree_Customer::delete($result->customer->id);
```
```
Warning: array_combine(): Both parameters should have at least 1 element in /vagrant/vendor/braintree/braintree_php/lib/Braintree/Result/Successful.php on line 87

Warning: Invalid argument supplied for foreach() in /vagrant/vendor/braintree/braintree_php/lib/Braintree/Result/Successful.php on line 53
```

This appears to result because the delete request returns HTTP 200 with an empty body. The `Braintree_Result_Successful` object apparently expects every result to include a body with elements.

This was replicated with version 2.40.0 but based on my cursory research, the latest version probably also throws these warnings.

**Comment by raymondberg** [comment]
Hi @marcguyer. We haven't been able to reproduce this on our side with either `2.40.0` or the latest(`3.5.0`), and this is not a great venue for troubleshooting individual issues. I would recommend opening a ticket with [Braintree support](https://support.braintreepayments.com) so you can share more details about your environment. I'm going to close this issue out now, but if you discover through support that this is a code issue feel free to reopen.

**Comment by marcguyer** [comment]
@raymondberg Hmm... Well, I might then assume that you don't have warnings enabled or warnings are logged instead of displayed in your test environment. Otherwise, replication couldn't be simpler:

```php
error_reporting(E_ALL);
ini_set('display_errors', true);

$merchantId = '[id]';
$publicKey = '[key]';
$privateKey = '[key]';

Braintree_Configuration::environment('sandbox');
Braintree_Configuration::merchantId($merchantId);
Braintree_Configuration::publicKey($publicKey);
Braintree_Configuration::privateKey($privateKey);
$result = Braintree_Customer::create(array(
  'firstName' =>'Test', 
  'lastName'  =>'Customer', 
  'email'     =>'test@example.com'
));
Braintree_Customer::delete($result->customer->id);
```

**Comment by sfscs** [comment]
Apologies for resurrecting this old issue, but it was the only mention of this problem I've found and I thought people might want to know the answer to this. @marcguyer 

Any time new instance of `Braintree_Result_Successful` aka `Braintree\Result\Successful` is created without any values for the constructor, such as in the above mentioned `Braintree_Customer::delete` function, the very last line of `Braintree_Result_Successful::_mapPropertyNamesToObjsToReturn` with execute an `array_combine` on two empty arrays which on version of PHP <5.4 issued E_WARNING and returned FALSE. 

This in turn caused the `foreach` loop in the constructor to emit a `Invalid argument supplied for foreach()` warning. Newer version of php properly return an empty array instead of FALSE, so this issue only happened with version of php 5.3 or below. This issue would still be happening in the current release of this library if not for the higher php version requirement which makes it a non-issue anymore.
